FROM python:3.11

WORKDIR /workspace

COPY requirements.txt /workspace/requirements.txt

RUN pip install -r requirements.txt

RUN apt-get update && \
    apt-get install -y make postgresql postgresql-contrib postgresql-client && \
    rm -rf /var/lib/apt/lists/*

EXPOSE 8002
