# Generated by Django 4.2.7 on 2024-05-30 17:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("org", "0001_initial"),
        ("query", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Label",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labels",
                        to="org.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Label",
                "verbose_name_plural": "Labels",
            },
        ),
        migrations.CreateModel(
            name="LabelReview",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.UUIDField(default=None, editable=False, null=True)),
                ("comment", models.TextField()),
                (
                    "old_category_id",
                    models.UUIDField(default=None, editable=False, null=True),
                ),
                (
                    "new_category_id",
                    models.UUIDField(default=None, editable=False, null=True),
                ),
            ],
            options={
                "verbose_name": "Label Review",
                "verbose_name_plural": "Label Reviews",
            },
        ),
        migrations.AddField(
            model_name="thread",
            name="label_id",
            field=models.UUIDField(default=None, editable=False, null=True),
        ),
        migrations.DeleteModel(
            name="Feedback",
        ),
        migrations.AddField(
            model_name="labelreview",
            name="thread",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review",
                to="query.thread",
            ),
        ),
    ]
