# Generated by Django 4.2.7 on 2024-05-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("query", "0002_label_labelreview_thread_label_id_delete_feedback_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="labelreview",
            name="new_category_id",
        ),
        migrations.RemoveField(
            model_name="labelreview",
            name="old_category_id",
        ),
        migrations.RemoveField(
            model_name="thread",
            name="label_id",
        ),
        migrations.AddField(
            model_name="labelreview",
            name="new_label",
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name="labelreview",
            name="old_label",
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name="thread",
            name="label",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name="Label",
        ),
    ]
