# Generated by Django 4.2.7 on 2024-05-30 18:24

import django.contrib.postgres.fields
from django.db import migrations, models
import query.src.enums


class Migration(migrations.Migration):
    dependencies = [
        ("org", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="labels",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=[
                    query.src.enums.LabelEnum["DISCOVERY"],
                    query.src.enums.LabelEnum["TROUBLESHOOTING"],
                ],
                help_text="List of labels associated with the project",
                size=None,
            ),
        ),
    ]
